const Types = {
  ON_SIGN_IN: 'ON_SIGN_IN',
  ON_SIGN_OUT: 'ON_SIGN_OUT',
  ON_DECK_ADDED: 'ON_DECK_ADDED',
  ON_DECK_CHANGED: 'ON_DECK_CHANGED',
  ON_DECK_REMOVED: 'ON_DECK_REMOVED',
  ON_CARD_ADDED: 'ON_CARD_ADDED',
  ON_CARD_CHANGED: 'ON_CARD_CHANGED',
  ON_CARD_REMOVED: 'ON_CARD_REMOVED'
};

export default Types;
