const Types = {
  AUTH_SIGNED_IN: 'AUTH_SIGNED_IN',
  AUTH_SIGNED_OUT: 'AUTH_SIGNED_OUT',
  ON_DECK_ADDED: 'ON_DECK_ADDED',
  ON_DECK_CHANGED: 'ON_DECK_CHANGED',
  ON_DECK_REMOVED: 'ON_DECK_REMOVED',
  ON_CARD_ADDED: 'ON_CARD_ADDED',
  ON_CARD_CHANGED: 'ON_CARD_CHANGED',
  ON_CARD_REMOVED: 'ON_CARD_REMOVED',
  CREATING_DECK_START: 'CREATING_DECK_START',
  CREATING_DECK_UPDATE_DECK: 'CREATING_DECK_UPDATE_DECK',
  CREATING_DECK_FINISH: 'CREATING_DECK_FINISH',
  CREATING_DECK_CANCEL: 'CREATING_DECK_CANCEL',
  EDITING_DECK_START: 'EDITING_DECK_START',
  EDITING_DECK_UPDATE_DECK: 'EDITING_DECK_UPDATE_DECK',
  EDITING_DECK_FINISH: 'EDITING_DECK_FINISH',
  EDITING_DECK_CANCEL: 'EDITING_DECK_CANCEL'
};

export default Types;
