const Types = {
  ON_SIGN_IN: 'ON_SIGN_IN',
  ON_SIGN_OUT: 'ON_SIGN_OUT',
  ON_DECK_ADDED: 'ON_DECK_ADDED',
  ON_DECK_CHANGED: 'ON_DECK_CHANGED',
  ON_DECK_REMOVED: 'ON_DECK_REMOVED',
  ON_CARD_ADDED: 'ON_CARD_ADDED',
  ON_CARD_CHANGED: 'ON_CARD_CHANGED',
  ON_CARD_REMOVED: 'ON_CARD_REMOVED',
  CREATING_DECK_START: 'CREATING_DECK_START',
  CREATING_DECK_UPDATE_DECK: 'CREATING_DECK_UPDATE_DECK',
  CREATING_DECK_FINISH: 'CREATING_DECK_FINISH',
  CREATING_DECK_CANCEL: 'CREATING_DECK_CANCEL',
};

export default Types;
